### ISSUE TITLE
mlPerBucket can't be < 0

### ISSUE THREAD

**Issue by magcicada** [M-W-K/GTCEFuContent#2]
Some mods can't allow the fluid buckets with blow 0 ml fluid, it will get carsh, such as PneumaticCraft: Repressurized.
`Caused by: java.lang.IllegalArgumentException: mlPerBucket can't be < 0!`
`    at me.desht.pneumaticcraft.common.PneumaticCraftAPIHandler.registerFuel(PneumaticCraftAPIHandler.java:114)`
`    at me.desht.pneumaticcraft.common.fluid.FluidFuelManager.registerFuels(FluidFuelManager.java:12)`
`    at me.desht.pneumaticcraft.PneumaticCraftRepressurized.postInit(PneumaticCraftRepressurized.java:184)`

**Comment by M-W-K** [comment]
Should be fixed in alpha release 2.0.1, can you confirm?

**Comment by M-W-K** [comment]
Considered fixed due to lack of response.
