### ISSUE TITLE
Crash on Server (java.lang.NoClassDefFoundError: gregtech/client/particle/GTLaserBeamParticle)

### ISSUE THREAD

**Issue by aking4125** [M-W-K/GTCEFuContent#3]
Hello, upon loading this mod onto the server. The server crashes with the following report:
[crash-2024-10-11_08.29.42-server.txt](https://github.com/user-attachments/files/17342752/crash-2024-10-11_08.29.42-server.txt)

We are using [Cleanroom](https://github.com/CleanroomMC/Cleanroom), which could be the reason for the error. It does work in Single Player using Cleanroom. Any ideas?

[debug.log](https://github.com/user-attachments/files/17342753/debug.log)

**Comment by M-W-K** [comment]
No, this is simply my mistake. The GTLaserBeamParticle class exists on the client only, yet I was trying to use it even when only the physical server is loaded. Can you confirm if release 2.0.4 fixes the issue?

**Comment by aking4125** [comment]
Will take a look and keep you posted

**Comment by M-W-K** [comment]
Considered fixed due to lack of response.

**Comment by aking4125** [comment]
Sorry. Yes it's fixed. Had IRL stuff going on.
